version: "3"

services:
  hello-app:
    container_name: hello-app
    # image: hello:2.0 > usando build no lugar
    build:
      context: .
      # dockerfile: Dockerfile > Padrão
    entrypoint: "/app/entrypoint.sh" # sobrescreve CMD do Dockerfile
    volumes:
      - ./:/app