version: "3"

services:
  app:
    container_name: app
    # image: codelab-node:1.0
    depends_on:
      - db
    build:
      context: .docker/node
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    entrypoint: .docker/node/entrypoint.sh
    volumes:
      - .:/home/node/app
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postgres
      - PGDATABASE=codelab
      - PGPORT=5432
    ports:
      - 3000:3000
  db:
    container_name: db
    image: postgres:16.2
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    # Usado no lugar de entrypoint pois não são vários comandos
    command: postgres -c log_statement=all
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    # Variáveis de ambiente do sistema operacional
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
