version: "1"

services:
  pg:
    container_name: pg
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
     - ".data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"